alert("Hello👋")
alert("Dahil clinick mo to may sasabihin ako")
alert("pindotin mo lang yung okay😅")
alert("baka naman")
alert("Malapit na tayo grumaduate")
alert("🥺wala ba kayong balak na mag ambagan para pambili ko ng Legendary Gun or Skin sa ML🥺")
alert("minsan lang to")
alert("sayang naman")
alert("regalo nyo nalang sakin")
alert("bigay nyo nalang sakin")
alert("Or")
alert("Send nyo saking gcash")
alert("kahit anong halaga tinatanggap ko")
alert("basta 50 pesos pataas")
alert("yun lang😊")
alert("have a good day/night😅😊")